### ISSUE TITLE
Need to upgrade antd version

### ISSUE THREAD

**Issue by asmfadholi** [LucasBassetti/react-typescript-antd-boilerplate#17]
Latest version of antd is cool. There are more new component added. It will help us to develop app. if possible I will help upgrade the version of antd. Thank you :)

**Comment by LucasBassetti** [comment]
Sure, can you do a PR for that? Thanks!

**Comment by asmfadholi** [comment]
Already created the PR. Please review this. #18

**Comment by LucasBassetti** [comment]
Thanks!
