### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by uncledent** [LucasBassetti/react-typescript-antd-boilerplate#3]
When started:

Failed to compile.

./src/screens/home/Home.tsx
Cannot find file: 'index.tsx' does not match the corresponding name on disk: './src/layout/Header/header'.

**Comment by LucasBassetti** [comment]
The import in Home.tsx is [import Header from '@layout/Header'](https://github.com/LucasBassetti/react-typescript-antd-boilerplate/blob/4ea7c45e04ae112b8c12eeea2b465605412d92cd/src/screens/home/Home.tsx#L9)

Not sure what's going on. Maybe you can try clean the cache

**Comment by mfaerevaag** [comment]
Got the same error, unfortunately. Tried `yarn cache clean` and `yarn start` again, but didn't help :-1:

**Comment by LucasBassetti** [comment]
In the `./src/screens/home/Home.tsx` try replace the `import Header from '@layout/Header'` to `import Header from '@layout/header'`

**Comment by mfaerevaag** [comment]
That fixed it. Thanks!
